[api]
open_ai = "xxxxxxxxxxxxxxxx"

[server]
port = 8090
password = "xxxxxxxxxxxxxxxx"

[employer]
name = "John"
full_name = "John Doe"
email = "john.doe@tuta.io"
phone = "+3312345"

[calendar]
username = "john.doe@tuta.io"
password = "xxxxxxxxxxxxxxxx"
server_url = "https://caldav.icloud.com"

[email]
username = "j4rvis.assistant@gmail.com"
password = "xxxxxxxxxxxxxxxx"
server_url = "smtp.gmail.com"
port = 465
